# Copyright 2020 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  id: 'builder'
  args: ['build', '-t', 'gcr.io/test-run-vic/myimage', '-f', './Dockerfile', '.']
 
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  id: 'pusher'
  args: ['push', 'gcr.io/test-run-vic/myimage']
  waitFor: ['builder']
  
  # Install dependencies
- name: python
  id: 'installer'
  entrypoint: pip
  args: ["install", "-r", "requirements.txt", "--user"]
  waitFor: ['pusher']
  
  
  #gcloud run deploy --image IMAGE \
  #--add-cloudsql-instances INSTANCE-CONNECTION-NAME \
  #--update-env-vars INSTANCE_CONNECTION_NAME="INSTANCE-CONNECTION-NAME"
  
  # Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  id: 'deployer'
  entrypoint: gcloud
  args: ['run', 'deploy', 'mycrservice', '--image', 'gcr.io/test-run-vic/myimage:latest', 
         '--region', 'europe-west1', '--platform', 'managed', '--allow-unauthenticated', 
         '--port','8080','--max-instances','2', '---add-cloudsql-instances', 'test-run-vic:us-central1:victest', '--update-env-vars','INSTANCE_CONNECTION_NAME=test-run-vic:us-central1:victest']
  env:
  - 'GOOGLE_APPLICATION_CREDENTIALS=test-run-vic-361644a10c27.json'
  - 'INSTANCE_CONNECTION_NAME=test-run-vic:us-central1:victest'
  - 'DB_USER=postgres'
  - 'DB_PASS=root'
  - 'DB_NAME=train'
  waitFor: ['installer']

- name: 'gcr.io/cloud-builders/gcloud'
  id: "Test step"
  entrypoint: "echo"
  args:
    - $$TEST
  secretEnv: ['TEST']
        
images:
- gcr.io/test-run-vic/myimage
 
availableSecrets:
  secretManager:
  - versionName: projects/test-run-vic/secrets/secrettest/versions/latest
    env: 'TEST'

        

 

